# ---------------------------------------------------------------------------
# Guided hook creation: the five starter hook-body templates (each returns
# the full .ps1 text for a generated hook), the custom-hook target-selection
# flow (Invoke-CustomHookTargets), and the Invoke-CreateHook stage machine
# that drives the "Create a new hook" menu choice.
#
# Split out of Setup-SyncGroup.ps1 (which had grown past the file-size review
# signal) because this is a genuine cohesive unit: generating a new hook
# script from a template is a distinct responsibility from rendering menus
# and driving install flows.
#
# Dot-sourced by Setup-SyncGroup.ps1 only. These functions rely on that
# script's ambient script-scope state and UI primitives ($C, $HooksDir,
# $InstallScript, $Utf8NoBom, Write-PhaseHeader, Write-Field, Write-MenuLine,
# Write-MenuTitle, Write-ErrorLine, Write-NoteLine, Read-Answer, Read-YesNo,
# Read-ClientChoice, Read-ProjectList, New-QuestionPrompt, Get-ExampleText,
# Get-ClientInstallArgs, Get-ClientInstallLabel, Get-Painted, Write-Log) -
# dot-sourcing splices these functions into the callers scope, and calls
# resolve at invocation time, so this is a normal one-directional
# dependency, not a layering violation.
# ---------------------------------------------------------------------------

# -------------------------------------------------- custom hook flow (2) ----
# Hook body templates. Each returns the full .ps1 text for a generated hook.
# Backticks escape $ so those tokens land literally in the generated file.
function Get-HookBody-ContextNote {
    param([string]$HookName, [string]$Message)
    $escaped = $Message.Replace("'", "''")
    return @"
# $HookName - injects a fixed context note into every matched event.
# Generated by Hook Maker. Edit this file freely - but if it is already
# installed anywhere, installed copies are self-contained: use "Update
# previously installed hooks" (or reinstall) to apply your edits there.
`$hookInput = [Console]::In.ReadToEnd() | ConvertFrom-Json
`$note = '$escaped'
@{ hookSpecificOutput = @{ hookEventName = `$hookInput.hook_event_name; additionalContext = `$note } } |
    ConvertTo-Json -Depth 5 -Compress
exit 0
"@
}

function Get-HookBody-PromptGuard {
    param([string]$HookName, [string[]]$Words)
    $wordList = (@($Words | ForEach-Object { "'" + $_.Replace("'", "''") + "'" })) -join ', '
    return @"
# $HookName - blocks prompts that contain forbidden words (UserPromptSubmit).
# Generated by Hook Maker. Edit the list freely - but if it is already
# installed anywhere, installed copies are self-contained: use "Update
# previously installed hooks" (or reinstall) to apply your edits there.
`$hookInput = [Console]::In.ReadToEnd() | ConvertFrom-Json
`$forbidden = @($wordList)
`$prompt = ''
if (`$null -ne `$hookInput.PSObject.Properties['prompt']) { `$prompt = [string]`$hookInput.prompt }
elseif (`$null -ne `$hookInput.PSObject.Properties['user_prompt']) { `$prompt = [string]`$hookInput.user_prompt }
foreach (`$word in `$forbidden) {
    if (`$prompt -match [regex]::Escape(`$word)) {
        @{ decision = 'block'; reason = ('Prompt contains a forbidden word: ' + `$word) } | ConvertTo-Json -Compress
        exit 0
    }
}
exit 0
"@
}

function Get-HookBody-ToolLogger {
    param([string]$HookName)
    return @"
# $HookName - appends one line per tool call to a log file next to this hook.
# Generated by Hook Maker. Edit this file freely - but if it is already
# installed anywhere, installed copies are self-contained: use "Update
# previously installed hooks" (or reinstall) to apply your edits there.
`$hookInput = [Console]::In.ReadToEnd() | ConvertFrom-Json
`$logFile = Join-Path (Split-Path -Parent `$MyInvocation.MyCommand.Path) '$HookName.log'
`$toolName = ''
if (`$null -ne `$hookInput.PSObject.Properties['tool_name']) { `$toolName = [string]`$hookInput.tool_name }
`$line = '[' + [DateTime]::UtcNow.ToString('yyyy-MM-dd HH:mm:ss') + ' UTC] ' + `$hookInput.hook_event_name + ' ' + `$toolName + ' cwd=' + `$hookInput.cwd
[System.IO.File]::AppendAllText(`$logFile, `$line + "``r``n", [System.Text.UTF8Encoding]::new(`$false))
exit 0
"@
}

function Get-HookBody-Skeleton {
    param([string]$HookName)
    return @"
# $HookName - custom hook skeleton. Generated by Hook Maker.
# The client sends ONE JSON event on stdin. Common fields:
#   hook_event_name, session_id, cwd
# Event-specific fields:
#   UserPromptSubmit: prompt   |   PreToolUse/PostToolUse: tool_name, tool_input
`$hookInput = [Console]::In.ReadToEnd() | ConvertFrom-Json

# TODO: your logic here.

# Stay silent:
exit 0

# Or inject context for the agent (SessionStart / UserPromptSubmit):
# @{ hookSpecificOutput = @{ hookEventName = `$hookInput.hook_event_name; additionalContext = 'note' } } |
#     ConvertTo-Json -Depth 5 -Compress
# exit 0
"@
}

function Get-HookBody-GitSync {
    param([string]$HookName)

    # Reuse the shipped Git-Sync-Check hook verbatim (renamed) so the template
    # never drifts from the maintained implementation. Its file body still uses
    # the identifier 'GitSyncCheck' internally (state key, comments), which is
    # what gets rewritten to the new hook name.
    $shipped = Join-Path $HooksDir 'Git-Sync-Check\Git-Sync-Check.ps1'
    $content = [System.IO.File]::ReadAllText($shipped)
    return $content.Replace('GitSyncCheck', $HookName).Replace("`r`n", "`n")
}

# The five guided templates. Details=$true means one question is asked.
$script:HookTemplates = @(
    [pscustomobject]@{ Key = '1'; Label = 'Context note'; Hint = 'injects a fixed note into every session/prompt'; Details = $true; DefaultEvents = @('SessionStart', 'UserPromptSubmit') }
    [pscustomobject]@{ Key = '2'; Label = 'Prompt guard'; Hint = 'blocks prompts containing forbidden words'; Details = $true; DefaultEvents = @('UserPromptSubmit') }
    [pscustomobject]@{ Key = '3'; Label = 'Tool logger'; Hint = 'logs every tool call to a file'; Details = $false; DefaultEvents = @('PreToolUse') }
    [pscustomobject]@{ Key = '4'; Label = 'Git sync check'; Hint = 'warns when the project is out of sync with its git remote'; Details = $false; DefaultEvents = @('SessionStart') }
    [pscustomobject]@{ Key = '5'; Label = 'Empty skeleton'; Hint = 'commented template for your own logic'; Details = $false; DefaultEvents = @('SessionStart', 'UserPromptSubmit') }
)

# Ask target projects, confirm, and install a hook into each. Returns 'done'
# (installed or user declined) or 'back' (user backed out at the first prompt).
function Invoke-CustomHookTargets {
    param(
        [Parameter(Mandatory = $true)][string]$HookPath,
        [Parameter(Mandatory = $true)]$Events
    )

    $hookName = Split-Path -Leaf $HookPath
    $stage = 0
    $clients = $null
    $targets = $null
    while ($true) {
        if ($stage -eq 0) {
            # Which client(s) gets this hook (Claude / Codex / both).
            $clients = Read-ClientChoice
            if ($null -eq $clients) {
                return 'back'
            }
            $stage = 1
            continue
        }
        if ($stage -eq 1) {
            $targets = Read-ProjectList -MinimumCount 1
            if ($null -eq $targets) {
                $stage = 0
                continue
            }
            $stage = 2
            continue
        }

        # stage 2: confirm
        Write-PhaseHeader 'Summary' $C.Summary '-'
        Write-Field 'hook script' $HookPath $C.LightBlue
        Write-Field 'events' (@($Events) -join ', ')
        Write-Field 'client' $clients
        Write-Field 'install' (Get-ClientInstallLabel $clients)
        Write-MenuTitle 'Target projects:'
        for ($i = 0; $i -lt $targets.Count; $i++) {
            Write-MenuLine ($i + 1) $targets[$i].Name $targets[$i].Root
        }
        Write-PhaseHeader 'Confirm' $C.Confirm '-'
        $confirm = Read-YesNo (New-QuestionPrompt 'Start now?' 'y/n' 'y') $true 'start custom hook install'
        if ($null -eq $confirm) {
            $stage = 1
            continue
        }
        if ($confirm -ne $true) {
            Write-NoteLine 'Canceled. Nothing was installed.'
            Write-Log 'INFO' 'CUSTOM' 'User declined at confirmation; no install.'
            return 'done'
        }

        Write-PhaseHeader 'Applying Changes' $C.Process '-'
        $clientArgs = Get-ClientInstallArgs $clients
        foreach ($target in $targets) {
            $installOutput = & $InstallScript -CustomHook $HookPath -Events @($Events) -TargetProject $target.Root @clientArgs *>&1
            foreach ($line in @($installOutput)) {
                Write-Log 'INFO' 'INSTALL' ([string]$line)
            }
            Write-Host ('  ' + (Get-Painted '+ hook installed in' $C.Green) + ' ' + (Get-Painted $target.Name $C.Bold) + '  ' + (Get-Painted $target.Root $C.Gray))
        }
        Write-PhaseHeader 'Completed' $C.Done '='
        Write-Host (Get-Painted ('  ' + $hookName + ' installed for: ' + (@($Events) -join ', ')) $C.White)
        Write-Host (Get-Painted '  Restart the Claude/Codex clients and review /hooks inside each project.' $C.White)
        Write-NoteLine '  Codex: run /hooks in each project and trust the new command before it runs.'
        Write-Log 'INFO' 'DONE' ('Custom hook installed: ' + $HookPath + ' | events=' + (@($Events) -join ',') + ' | clients=' + $clients + ' | projects=' + $targets.Count)
        return 'done'
    }
}

# Guided hook creation as a stage machine. Back (0) steps ONE stage back; back
# at the first stage returns 'back' so the caller redisplays its menu.
function Invoke-CreateHook {
    Write-Log 'INFO' 'CUSTOM' 'Guided hook creation started.'
    Write-PhaseHeader 'Create a New Hook' $C.Input '-'

    $hookName = ''
    $template = $null
    $details = ''
    $stage = 0

    while ($true) {
        switch ($stage) {
            0 {
                # Hook name
                $namePrompt = New-QuestionPrompt 'Hook name' ('letters, digits and dashes; example: ' + (Get-ExampleText 'MyContextHook')) $null
                $value = Read-Answer $namePrompt 'new hook name'
                if ($value -eq '0') {
                    return 'back'
                }
                if ($value -notmatch '^[A-Za-z][A-Za-z0-9-]*$') {
                    Write-ErrorLine 'Use only letters, digits and dashes, starting with a letter.'
                    break
                }
                if (Test-Path -LiteralPath (Join-Path $HooksDir $value)) {
                    Write-ErrorLine ('A hook with this name already exists: ' + (Join-Path $HooksDir $value))
                    break
                }
                $hookName = $value
                $stage = 1
            }
            1 {
                # Template
                Write-MenuTitle 'Template:'
                foreach ($t in $script:HookTemplates) {
                    Write-MenuLine ([int]$t.Key) $t.Label ('(' + $t.Hint + ')')
                }
                $value = Read-Answer (New-QuestionPrompt 'Select a template' $null '1') 'hook template'
                if ($value -eq '0') {
                    $stage = 0
                    break
                }
                if ($value -eq '') {
                    $value = '1'
                }
                $picked = $script:HookTemplates | Where-Object { $_.Key -eq $value }
                if ($null -eq $picked) {
                    Write-ErrorLine 'Enter 1, 2, 3, 4 or 5.'
                    break
                }
                $template = $picked
                $details = ''
                if ($template.Details) {
                    $stage = 2
                }
                else {
                    $stage = 3
                }
            }
            2 {
                # Template-specific question (only for Details templates)
                if ($template.Key -eq '1') {
                    $value = Read-Answer (New-QuestionPrompt 'Context note text' ('shown to the agent on every matched event; example: ' + (Get-ExampleText 'Always answer in Persian.')) $null) 'context note text'
                    if ($value -eq '0') {
                        $stage = 1
                        break
                    }
                    if ($value -eq '') {
                        Write-ErrorLine 'This value cannot be empty. Try again.'
                        break
                    }
                    $details = $value
                    $stage = 3
                }
                elseif ($template.Key -eq '2') {
                    $value = Read-Answer (New-QuestionPrompt 'Forbidden words' ('comma separated; example: ' + (Get-ExampleText 'password,api key')) $null) 'forbidden words'
                    if ($value -eq '0') {
                        $stage = 1
                        break
                    }
                    $words = @($value.Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
                    if ($words.Count -eq 0) {
                        Write-ErrorLine 'Enter at least one word.'
                        break
                    }
                    $details = $words -join ','
                    $stage = 3
                }
                else {
                    $stage = 3
                }
            }
            3 {
                # Build + write the hook folder (script + .env.example), then
                # ask whether to install now.
                $hookFolder = Join-Path $HooksDir $hookName
                $hookPath = Join-Path $hookFolder ($hookName + '.ps1')
                switch ($template.Key) {
                    '1' { $body = Get-HookBody-ContextNote -HookName $hookName -Message $details }
                    '2' { $body = Get-HookBody-PromptGuard -HookName $hookName -Words @($details.Split(',')) }
                    '3' { $body = Get-HookBody-ToolLogger -HookName $hookName }
                    '4' { $body = Get-HookBody-GitSync -HookName $hookName }
                    '5' { $body = Get-HookBody-Skeleton -HookName $hookName }
                }
                New-Item -ItemType Directory -Path $hookFolder -Force | Out-Null
                [System.IO.File]::WriteAllText($hookPath, $body.Replace("`n", "`r`n"), $Utf8NoBom)
                $envExample = '# ' + $hookName + " configuration.`n" +
                    "# Copy this file to `".env`" (same folder) and edit. `".env`" is git-ignored.`n`n" +
                    "# Events to register on (comma separated).`n" +
                    'EVENTS=' + ($template.DefaultEvents -join ',') + "`n`n" +
                    "# Project roots for config-based install from the Hook Maker menu (semicolon separated).`n" +
                    "TARGET_PROJECTS=`n`n" +
                    "# Which client(s) to install for from the Hook Maker menu: Both, Claude, or Codex.`n" +
                    "CLIENTS=Both`n"
                [System.IO.File]::WriteAllText((Join-Path $hookFolder '.env.example'), $envExample.Replace("`n", "`r`n"), $Utf8NoBom)
                Write-Host ('  ' + (Get-Painted '+ created' $C.Green) + ' ' + (Get-Painted $hookPath $C.LightBlue))
                Write-Host ('  ' + (Get-Painted '+ created' $C.Green) + ' ' + (Get-Painted (Join-Path $hookFolder '.env.example') $C.LightBlue))
                Write-Field 'template' $template.Label
                Write-Field 'default events' ($template.DefaultEvents -join ', ')
                Write-Log 'INFO' 'CUSTOM' ('Hook created: ' + $hookPath + ' | template=' + $template.Key)

                $install = Read-YesNo (New-QuestionPrompt 'Install it into projects now?' 'y/n' 'y') $true 'install created hook'
                if ($null -eq $install) {
                    if ($template.Details) { $stage = 2 } else { $stage = 1 }
                    break
                }
                if ($install -ne $true) {
                    Write-NoteLine ('Saved in hooks\. Install it later via "Install an existing hook".')
                    return 'done'
                }
                $result = Invoke-CustomHookTargets -HookPath $hookPath -Events $template.DefaultEvents
                if ($result -eq 'back') {
                    break   # re-show the install question
                }
                return 'done'
            }
        }
    }
}
